### PR TITLE
Adding an ADOP Cartridge

### PR DESCRIPTION
**Pull request by kramos**
Hi 
I've added a folder called ADOP which contains the necessary goodness so that this project can be loaded into ADOP complete with a CD pipeline.
https://accenture.github.io/adop-docker-compose/
This means that anyone with an ADOP instance could more easily explore and contribute to Alexia.
Happy to provide a demo if you aren't familiar with ADOP.

### CODE REVIEW

**Comment by Glogo** [comment]
Hi kramos,
thank you for your collaboration

I need to clarify some things first:
- Alexia is a Node.js Framework and it is installed into node_modules folder of other Node.js projects depending on it. Since your cartridge is inside our main directory I will be installed as dependency in every project using Alexia. I don't think thats expected behaviour. Alexia does not need jenkins job, but projects using alexia could
- Would it make more sense to add this cartridge into the starter kit project? (not yet open sourced. It will be simple Hello World project created using Alexia)

Thank you and sorry for late reponse
Michael

**Comment by kramos** [comment]
Hi Michael
Thanks for getting back to me and for you help. 
Would it fix the problem if I added a .npmignore file containing the string "adop"?
Sorry for my ignorance.
Thanks,
Markos

**Comment by Glogo** [comment]
Yes, that would help to solve the problem of installing it to all clients. I would like to get more familiar with ADOP though and possibly help extend our main README so it is more clear for other users as well

Would you be able to provide me some short demo and example use of your cartridge?

Thank you,
Michael

**Comment by Glogo** [comment]
Merging now, as the `adop` directory won't be included in production installations anyway.
In `package.json` we have:
```
  "files": [
    "LICENSE",
    "README.md",
    "src/"
  ],
```

So my original concert won't affect us.

Let me know when its possible to join adop demo to see it in action. We could extend our README and link to some relevant material.

**Comment by kubacka** [comment]
@kramos Thanks for contributions but as @Glogo mentioned earlier Alexia is NodeJS library. We already use Travis for CI (for tests) and we just spoiled alexia code with something that we don't use at all. It doesn't make sense for me to to be part of Alexia but it makes sense to add it to alexia-starter-kit (sample alexia app to start with) or separate repository (e.g. alexia-starter-kit-adop).

**Pull request merged**
